M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date Mon 30 Jan 2023 13:17:47 GMT
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-01-30T13:17:47+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
%
G90
G05
T1
X86.815Y-61.35
X91.665Y-61.35
T2
X86.515Y-58.32
X91.965Y-58.32
T0
M30
